# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: ReleaseGate
    steps:
      - task: InvokeRESTAPI@1
    displayName: 'Invoke REST API: POST'
    inputs:
      connectedServiceName: 7edc7064-e590-4f62-93e7-524977f989ad
      body: " {\n            \"releaseNumber\": \"$(Release.ReleaseId)\",\n            \"projectName\": \"$(System.TeamProject)\"\n         }\n  "
      waitForCompletion: 'true'
